### ISSUE TITLE
enable compliance framework

### ISSUE THREAD

**Issue by ehaselwanter** [mondoohq/terraform-provider-mondoo#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chris-rock** [comment]
I propose a definition similar to our policies:

```
resource "mondoo_framework_assignment" "space" {
  space_id = mondoo_space.my_space.id

  policies = [
    "//policy.api.mondoo.app/policies/mondoo-aws-security",
  ]

  state = "enabled"
  
  activate_policies   = true
  
  # default is false, allows only setting specific policies
  partial_update = false
}
```

**Comment by chris-rock** [comment]
I added sample requests to our API examples https://github.com/mondoohq/samples/pull/63/files

**Comment by Pauti** [comment]
We implemented the issue in the following PR: https://github.com/mondoohq/terraform-provider-mondoo/pull/108
