### ISSUE TITLE
Provider Extension: Domain/IP Address / Website

### ISSUE THREAD

**Issue by Pauti** [mondoohq/terraform-provider-mondoo#57]
**Is your feature request related to a problem? Please describe.**
Currently, integrating domain/website scanning with the Terraform provider requires manual configuration via the dashboard. Even though this process isn't complex, there is a need to extend the capabilities of the Terraform provider to integrate with domains/websites, adding them automatically for scanning purposes to simplify the process.

**Describe the solution you'd like**

### Required

- `host` (String) Domain name or IP address.
- `space_id` (String) Mondoo Space Identifier.

### Optional

- `http` (Boolean) Enable HTTP port.
- `https` (Boolean) Enable HTTPS port.

### Read-Only

- `mrn` (String) Integration identifier

**Describe alternatives you've considered**
As this process doesn't require much setup and configuration, the process could also be solely handled via the dashboard.

**Additional context**

Implementation (@Pauti):
```
terraform {
  required_providers {
    mondoo = {
      source = "mondoohq/mondoo"
    }
  }
}

provider "mondoo" {
  region = "us"
}

// Create a new space
resource "mondoo_space" "domain_space" {
  name   = "My Space Name"
  org_id = "your-org-1234567"
}

// Setup the Domain integration
resource "mondoo_integration_domain" "domain_integration" {
  space_id = mondoo_space.domain_space.id
  host     = "example.com"
  https    = true
  http     = false
}
```

Pull Request: tba

**Comment by chris-rock** [comment]
Added by https://github.com/mondoohq/terraform-provider-mondoo/pull/71
