### ISSUE TITLE
Provider Extension: Microsoft 365 Integration

### ISSUE THREAD

**Issue by Pauti** [mondoohq/terraform-provider-mondoo#59]
_**WIP / TBD**_
**Is your feature request related to a problem? Please describe.**
Currently, integrating Microsoft 365 tenant assets with the Terraform provider requires manual configuration, involving several steps and potential for errors. There is a need to extend the capabilities of the Terraform provider to integrate with Microsoft 365 tenant, adding Microsoft 365-related assets (Azure AD, MFA, Sharepoint, ...) automatically. 

**Describe the solution you'd like**
Variables:
- tenant ID
- client ID
- PEM

**Describe alternatives you've considered**

**Additional context**
#### Required

- `client_id` (String) Azure Client ID.
- `credentials` (Attributes) (see [below for nested schema](#nestedatt--credentials))
- `name` (String) Name of the integration.
- `space_id` (String) Mondoo Space Identifier.
- `tenant_id` (String) Azure Tenant ID.

#### Read-Only

- `mrn` (String) Integration identifier

<a id="nestedatt--credentials"></a>
#### Nested Schema for `credentials`

Required:

- `pem_file` (String, Sensitive) PEM file for Ms365 integration.

PR: https://github.com/mondoohq/terraform-provider-mondoo/pull/91

**Comment by chris-rock** [comment]
That would be a great addition!
